version: '3'

networks:
  default:
    name: traefik
    external: true

services:
  web:
    image: ghcr.io/cords-ai/cords-node-docker-image:v1.0.1
    build: ./docker
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: node .output/server/index.mjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.$ROUTERNAME.rule=Host(`$HOSTNAME`)
      - traefik.http.routers.$ROUTERNAME.tls=true
      - traefik.http.services.$ROUTERNAME.loadbalancer.server.port=3000

  dev:
    image: ghcr.io/cords-ai/cords-node-docker-image:v1.0.1
    profiles: ['manual']
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    user: "1000:1000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.$ROUTERNAME.rule=Host(`$HOSTNAME`)
      - traefik.http.routers.$ROUTERNAME.tls=true
      - traefik.http.services.$ROUTERNAME.loadbalancer.server.port=3000

  jsonserver:
    image: ghcr.io/cords-ai/cords-node-docker-image:v1.0.1
    profiles: ['manual']
    hostname: backend-$HOSTNAME
    volumes:
      - .:/app
    working_dir: /app/data
    command: json-server db.json --watch
    labels:
      - traefik.enable=true
      - traefik.http.routers.$ROUTERNAME-backend.rule=Host(`backend-$HOSTNAME`)
      - traefik.http.routers.$ROUTERNAME-backend.tls=true
      - traefik.http.services.$ROUTERNAME-backend.loadbalancer.server.port=3001

  test:
    image: ghcr.io/cords-ai/cords-node-docker-image:v1.0.1
    profiles: ['manual']
    volumes:
      - .:/app
    working_dir: /app
    command: ./tools/test
    user: "1000:1000"
