version: '3'

networks:
  default:
    name: traefik
    external: true

services:
  web:
    image: ghcr.io/cords-connect/node:1.0.0
    build: ./docker
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: node .output/server/index.mjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.$ROUTERNAME.rule=Host(`$HOSTNAME`)
      - traefik.http.routers.$ROUTERNAME.tls=true
      - traefik.http.routers.$ROUTERNAME.entrypoints=https
      - traefik.http.services.$ROUTERNAME.loadbalancer.server.port=3000

  dev:
    image: ghcr.io/cords-connect/node:1.0.0
    profiles: ['manual']
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    user: "1000:1000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.$ROUTERNAME.rule=Host(`$HOSTNAME`)
      - traefik.http.routers.$ROUTERNAME.tls=true
      - traefik.http.routers.$ROUTERNAME.entrypoints=https
      - traefik.http.services.$ROUTERNAME.loadbalancer.server.port=3000

  test:
    image: ghcr.io/cords-connect/node:1.0.0
    profiles: ['manual']
    volumes:
      - .:/app
    working_dir: /app
    command: ./tools/test
    user: "1000:1000"
